import { products } from './catalog.mjs';
import { cleanCart,totals,addItem,itemKey,stockFor,validateDelivery,validateContact,readStorage,writeStorage,escapeHtml as e,yen } from './core.mjs';
import { t,url,titleOf,productUrl,photo,collectionResults,cartRows,summary,emptyBag } from './views.mjs';
import { errorText } from './info.mjs';
import { sampleDelivery,paymentLabel } from './checkout.mjs';
import { renderPage,mainContent } from './render.mjs';
import { registerStoreTools } from './webmcp.mjs';
const safeStorage=name=>{try{return window[name]}catch{return {getItem(){return null},setItem(){throw new Error('Storage unavailable')},removeItem(){}}}};
const local=safeStorage('localStorage'),session=safeStorage('sessionStorage');
const KEYS={cart:'aseed.bag.v2',favorites:'aseed.saved.v2',lang:'aseed.lang.v2',receipt:'aseed.receipt.v2'};
const params=new URLSearchParams(location.search);
const storedFavorites=readStorage(local,KEYS.favorites,[]);
const initialCart=readStorage(local,KEYS.cart,readStorage(local,'aseed.cart.v1',[]));
const storedReceipt=readStorage(session,KEYS.receipt,null);
const validReceipt=r=>r&&typeof r.id==='string'&&!Number.isNaN(Date.parse(r.date))&&Array.isArray(r.items)&&r.items.length>0&&r.items.every(i=>typeof i.name==='string'&&typeof i.nameJa==='string'&&Number.isFinite(i.price)&&Number.isInteger(i.qty)&&i.qty>0)&&['subtotal','shipping','total'].every(k=>Number.isFinite(r[k]));
let ctx={page:document.body.dataset.page||'index',lang:params.get('lang')==='en'?'en':params.get('lang')==='ja'?'ja':readStorage(local,KEYS.lang,'ja')==='en'?'en':'ja',id:params.get('id')||document.body.dataset.product||'',cart:cleanCart(initialCart,products),favorites:Array.isArray(storedFavorites)?storedFavorites.filter(id=>products.some(p=>p.id===id)):[],query:params.get('q')||'',category:params.get('cat')||'all',sort:params.get('sort')||'featured',onlyFavorites:params.get('favorites')==='1',selection:{},checkout:{step:0,delivery:{},payment:'card-demo'},receipt:validReceipt(storedReceipt)?storedReceipt:null};
const root=document.querySelector('#site-content');
const cartDialog=document.querySelector('#cart-dialog');
const zoomDialog=document.querySelector('#zoom-dialog');
let cartOpener=null,searchTimer,toastTimer,reviewFingerprint='',completing=false,contactDraft={},contactMessage='';
function toast(text){let el=document.querySelector('#toast');el.textContent=text;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.hidden=true},4300);}
function save(key,value){const ok=writeStorage(local,key,value);if(!ok)toast(t(ctx.lang,'このブラウザーでは保存できません。画面を閉じると内容は失われます。','Storage is unavailable. Your selection will be lost when this page closes.'));return ok;}
function meta(){document.documentElement.lang=ctx.lang;document.body.dataset.page=ctx.page;const p=products.find(p=>p.id===ctx.id);const titles={index:'Quiet forms. Everyday life.',store:t(ctx.lang,'コレクション','Collection'),cart:t(ctx.lang,'バッグ','Your bag'),checkout:t(ctx.lang,'購入手続き','Checkout'),order:t(ctx.lang,'デモ注文完了','Demo order complete'),lookbook:'Lookbook',about:'Our story',contact:t(ctx.lang,'お問い合わせ','Contact'),'case-study':t(ctx.lang,'制作事例','Case study'),privacy:t(ctx.lang,'プライバシーポリシー','Privacy policy'),legal:t(ctx.lang,'特定商取引法に基づく表記','Commerce disclosure'),terms:t(ctx.lang,'利用規約','Terms'),shipping:t(ctx.lang,'配送・返品','Shipping & returns'),guide:t(ctx.lang,'ご利用ガイド','Shopping guide')};document.title=`${ctx.page==='product'?(p?titleOf(p,ctx.lang):'Not found'):titles[ctx.page]||'Not found'} — aseed`;const description=document.querySelector('meta[name=description]');if(description)description.content=ctx.page==='product'&&p?(ctx.lang==='ja'?p.desc:p.descEn):t(ctx.lang,'aseed — 余白を纏う。アパレルのコンセプトストア。','aseed — Quiet forms. Everyday life. An apparel concept store.');}
function render(){root.innerHTML=renderPage(ctx);meta();bindAfterRender();}
function renderMain(){document.querySelector('#main').innerHTML=mainContent(ctx);meta();bindAfterRender();}
function bindAfterRender(){if(ctx.page==='contact'&&Object.keys(contactDraft).length){const f=document.querySelector('#contact-form');if(f)for(const [name,val]of Object.entries(contactDraft)){const el=f.elements.namedItem(name);if(el){if(el.type==='checkbox')el.checked=!!val;else el.value=val;}}}}
function bagCount(){document.querySelectorAll('[data-bag-count]').forEach(el=>el.textContent=totals(ctx.cart,products).count);const button=document.querySelector('.bag-link');if(button)button.setAttribute('aria-label',`${t(ctx.lang,'バッグを開く','Open shopping bag')} (${totals(ctx.cart,products).count})`);}
function persistCart(){ctx.cart=cleanCart(ctx.cart,products);save(KEYS.cart,ctx.cart);bagCount();}
function rememberFocus(){const el=document.activeElement;return el?{action:el.dataset.action,key:el.dataset.key,delta:el.dataset.delta}:null;}
function restoreFocus(scope,focused){if(!focused?.action)return;const candidate=[...scope.querySelectorAll('[data-action]')].find(el=>el.dataset.action===focused.action&&el.dataset.key===focused.key&&el.dataset.delta===focused.delta&&!el.disabled);candidate?.focus({preventScroll:true});}
function refreshCart(){const focus=rememberFocus();persistCart();if(cartDialog.open){drawCart();restoreFocus(cartDialog,focus);}if(ctx.page==='cart'){renderMain();restoreFocus(root,focus);}if(ctx.page==='checkout'){captureDelivery();ctx.checkout.step=0;reviewFingerprint='';renderMain();toast(t(ctx.lang,'バッグが更新されました。注文内容をご確認ください。','Your bag changed. Please review the order again.'));}}
function drawCart(added=false){cartDialog.innerHTML=`<div class="dialog-heading"><h2 id="cart-title">${t(ctx.lang,'ショッピングバッグ','Your bag')} (${totals(ctx.cart,products).count})</h2><button class="close-button" data-action="close-cart" aria-label="${t(ctx.lang,'閉じる','Close')}">×</button></div>${added?`<p role="status">✓ ${t(ctx.lang,'バッグに追加しました','Added to your bag')}</p>`:''}${ctx.cart.length?cartRows(ctx,true)+summary(ctx):emptyBag(ctx.lang)}<div class="drawer-links"><a href="${url('cart',ctx.lang)}">${t(ctx.lang,'バッグを見る','View bag')}</a><button data-action="close-cart">${t(ctx.lang,'買い物を続ける','Continue exploring')}</button></div>`;}
function openCart(added=false){cartOpener=document.activeElement;drawCart(added);if(!cartDialog.open)cartDialog.showModal();}
function closeCart(){cartDialog.close();if(cartOpener?.isConnected)cartOpener.focus({preventScroll:true});}
function filterUrl(){const next=new URL(location.href);for(const k of ['q','cat','sort','favorites'])next.searchParams.delete(k);if(ctx.query)next.searchParams.set('q',ctx.query);if(ctx.category!=='all')next.searchParams.set('cat',ctx.category);if(ctx.sort!=='featured')next.searchParams.set('sort',ctx.sort);if(ctx.onlyFavorites)next.searchParams.set('favorites','1');next.searchParams.set('lang',ctx.lang);history.replaceState(null,'',next);}
function updateResults(){document.querySelector('#collection-results').innerHTML=collectionResults(ctx);filterUrl();}
function favorite(id){if(!products.some(p=>p.id===id))return;const exists=ctx.favorites.includes(id);ctx.favorites=exists?ctx.favorites.filter(x=>x!==id):[...ctx.favorites,id];save(KEYS.favorites,ctx.favorites);document.querySelectorAll('[data-action="favorite"]').forEach(btn=>{if(btn.dataset.id!==id)return;btn.setAttribute('aria-pressed',String(!exists));btn.classList.toggle('is-saved',!exists);btn.innerHTML=btn.classList.contains('save-detail')?`${!exists?'♥':'♡'} ${!exists?t(ctx.lang,'お気に入りに保存済み','Saved to your collection'):t(ctx.lang,'お気に入りに保存','Save for later')}`:(!exists?'♥':'♡');});if(ctx.page==='store'&&ctx.onlyFavorites)updateResults();toast(exists?t(ctx.lang,'お気に入りから削除しました','Removed from saved pieces'):t(ctx.lang,'お気に入りに保存しました','Saved for later'));}
function productSubmit(){const p=products.find(p=>p.id===ctx.id);const {color=p.colors[0],size,qty=1}=ctx.selection;const result=addItem(ctx.cart,p,color,size,qty,products);if(!result.ok){const msg=result.error==='stock'?t(ctx.lang,'バッグ内の数量と合わせて在庫上限を超えています。','This exceeds the available demo stock, including items already in your bag.'):t(ctx.lang,'サイズを選択してください。','Please select a size.');document.querySelector('#product-error').textContent=msg;if(result.error==='selection'){document.querySelector('#size-field').scrollIntoView({block:'center'});document.querySelector('[name="size"]:not(:disabled)')?.focus({preventScroll:true});}return false;}ctx.cart=result.items;persistCart();openCart(true);return true;}
function showErrors(form,errors){for(const el of form.querySelectorAll('[aria-invalid]'))el.removeAttribute('aria-invalid');for(const el of form.querySelectorAll('.field-error'))el.textContent='';for(const [key,code] of Object.entries(errors)){const el=form.elements.namedItem(key);if(el)el.setAttribute('aria-invalid','true');const target=form.querySelector(`#error-${key}`);if(target)target.textContent=errorText(code,ctx.lang);}const first=Object.keys(errors)[0];if(first)form.elements.namedItem(first)?.focus();}
function captureDelivery(){const f=document.querySelector('#delivery-form');if(f)ctx.checkout.delivery=Object.fromEntries(new FormData(f));}
function checkoutStep(step){captureDelivery();if(step>0&&Object.keys(validateDelivery(ctx.checkout.delivery)).length)step=0;ctx.checkout.step=step;renderMain();document.querySelector('.checkout-form h2')?.scrollIntoView({block:'start'});const main=document.querySelector('#main');main.focus({preventScroll:true});}
function completeOrder(form){if(completing)return;if(!form.elements.reviewConsent.checked)return;const current=cleanCart(ctx.cart,products);if(!current.length||JSON.stringify(current)!==reviewFingerprint||Object.keys(validateDelivery(ctx.checkout.delivery)).length||!['card-demo','bank-demo'].includes(ctx.checkout.payment)){document.querySelector('#checkout-error').textContent=t(ctx.lang,'注文内容が変わりました。配送情報から再確認してください。','Your order changed. Please review it again from the delivery step.');return;}
 completing=true;document.querySelector('#place-order').disabled=true;const sum=totals(current,products);const r={id:'DEMO-'+crypto.randomUUID().slice(0,8).toUpperCase(),date:new Date().toISOString(),items:current.map(i=>{const p=products.find(p=>p.id===i.id);return {...i,name:p.name,nameJa:p.nameJa,price:p.price};}),...sum};ctx.receipt=r;ctx.checkout={step:0,delivery:{},payment:'card-demo'};ctx.cart=[];persistCart();const saved=writeStorage(session,KEYS.receipt,r);if(saved)location.assign(url('order',ctx.lang));else{ctx.page='order';history.pushState(null,'',url('order',ctx.lang));render();window.scrollTo(0,0);toast(t(ctx.lang,'注文控えは現在の画面内のみで表示します。必要ならダウンロードしてください。','This summary is available only on this page. Download it to keep a copy.'));}}
function downloadReceipt(){const r=ctx.receipt;if(!r)return;const text=`ASEED — DEMO ORDER SUMMARY\nNOT A RECEIPT / NO PAYMENT OR DELIVERY\n${r.id}\n${r.date}\n\n${r.items.map(i=>`${i.name} / ${i.color} / ${i.size} / Qty ${i.qty} / ${yen(i.price*i.qty,'en')}`).join('\n')}\n\nSubtotal: ${yen(r.subtotal,'en')}\nShipping: ${yen(r.shipping,'en')}\nTotal: ${yen(r.total,'en')}\n\nAI-generated product concepts. No real transaction. No delivery information retained.`;const objectUrl=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=objectUrl;a.download=`aseed-${r.id}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(objectUrl),1000);}
document.addEventListener('click',async event=>{const btn=event.target.closest('[data-action]');if(!btn)return;const action=btn.dataset.action;
 if(action==='language'){captureDelivery();const f=document.querySelector('#contact-form');if(f)contactDraft={...Object.fromEntries(new FormData(f)),consent:f.elements.consent.checked};ctx.lang=ctx.lang==='ja'?'en':'ja';save(KEYS.lang,ctx.lang);const u=new URL(location.href);u.searchParams.set('lang',ctx.lang);history.replaceState(null,'',u);if(cartDialog.open)closeCart();render();return;}
 if(action==='menu'){const nav=document.querySelector('#mobile-nav'),isOpen=!nav.hidden;nav.hidden=isOpen;btn.setAttribute('aria-expanded',String(!isOpen));return;}
 if(action==='open-cart'){openCart();return;}if(action==='close-cart'){closeCart();return;}
 if(action==='favorite'){favorite(btn.dataset.id);return;}
 if(action==='category'){ctx.category=btn.dataset.category;document.querySelectorAll('[data-action="category"]').forEach(el=>{el.classList.toggle('active',el===btn);el.setAttribute('aria-pressed',String(el===btn));});updateResults();return;}
 if(action==='filter-favorites'){ctx.onlyFavorites=!ctx.onlyFavorites;filterUrl();renderMain();document.querySelector('[data-action="filter-favorites"]').focus({preventScroll:true});return;}
 if(action==='reset-filters'){Object.assign(ctx,{query:'',category:'all',onlyFavorites:false,sort:'featured'});filterUrl();renderMain();document.querySelector('#search').focus();return;}
 if(action==='view'){ctx.selection.view=btn.dataset.view;const focusView=btn.dataset.view;renderMain();[...document.querySelectorAll('[data-action="view"]')].find(el=>el.dataset.view===focusView)?.focus({preventScroll:true});return;}
 if(action==='zoom'){const img=document.querySelector('#main-product-photo');zoomDialog.innerHTML=`<button class="close-button" data-action="close-zoom" aria-label="${t(ctx.lang,'閉じる','Close')}">×</button><img src="${e(img.getAttribute('src'))}" alt="${e(img.alt)}">`;zoomDialog.showModal();return;}
 if(action==='close-zoom'){zoomDialog.close();return;}
 if(action==='size-guide'){const guide=document.querySelector('#size-guide');guide.open=true;guide.scrollIntoView({block:'center'});guide.querySelector('summary').focus({preventScroll:true});return;}
 if(action==='mobile-buy'){if(ctx.selection.size)productSubmit();else{document.querySelector('#size-field').scrollIntoView({block:'center'});document.querySelector('[name="size"]:not(:disabled)')?.focus({preventScroll:true});}return;}
 if(action==='quantity'||action==='remove'){const i=ctx.cart.find(i=>itemKey(i.id,i.color,i.size)===btn.dataset.key);if(!i)return;if(action==='remove'){ctx.cart=ctx.cart.filter(x=>x!==i);toast(t(ctx.lang,'バッグから削除しました','Removed from your bag'));}else {const p=products.find(p=>p.id===i.id);i.qty=Math.max(1,Math.min(Math.min(9,stockFor(p,i.color,i.size)),i.qty+Number(btn.dataset.delta)));}refreshCart();return;}
 if(action==='sample-delivery'){ctx.checkout.delivery={...sampleDelivery};renderMain();document.querySelector('#delivery-form input').focus();return;}
 if(action==='checkout-step'){checkoutStep(Number(btn.dataset.step));return;}
 if(action==='download-receipt'){downloadReceipt();return;}
 if(action==='sample-contact'){contactDraft={name:'Demo Guest',email:'demo@example.com',topic:'website',message:t(ctx.lang,'アパレルブランドのサイト制作について相談したいです。これは送信しないデモ用の文章です。','I would like to discuss a website for an apparel brand. This is a sample message for the demo and will not be sent.'),consent:false};bindAfterRender();document.querySelector('#contact-form input').focus();return;}
 if(action==='reset-contact'){contactDraft={};contactMessage='';renderMain();return;}
 if(action==='copy-contact'){try{await navigator.clipboard.writeText(contactMessage);toast(t(ctx.lang,'お問い合わせ文をコピーしました','Message copied'));}catch{toast(t(ctx.lang,'コピーできませんでした。本文を選択してコピーしてください。','Copy unavailable. Select the message text and copy it manually.'));}return;}
 if(action==='clear-data'){for(const key of Object.values(KEYS)){try{local.removeItem(key);session.removeItem(key)}catch{}}for(const key of ['aseed.cart.v1','aseed.fav.v1']){try{local.removeItem(key)}catch{}}ctx.cart=[];ctx.favorites=[];ctx.receipt=null;bagCount();toast(t(ctx.lang,'この端末のデモ保存データを削除しました','Demo data on this device has been cleared'));return;}
});
document.addEventListener('change',event=>{const el=event.target;if(el.closest('#product-form')){const p=products.find(p=>p.id===ctx.id);if(el.name==='color'){ctx.selection.color=el.value;ctx.selection.view='front';if(!stockFor(p,el.value,ctx.selection.size))ctx.selection.size='';}if(el.name==='size')ctx.selection.size=el.value;if(el.name==='qty')ctx.selection.qty=Number(el.value);if(ctx.selection.size)ctx.selection.qty=Math.min(ctx.selection.qty||1,stockFor(p,ctx.selection.color||p.colors[0],ctx.selection.size));const name=el.name,value=el.value;renderMain();const target=[...document.querySelectorAll(`[name="${name}"]`)].find(x=>x.value===value);target?.focus({preventScroll:true});}if(el.id==='sort'){ctx.sort=el.value;updateResults();}});
document.addEventListener('input',event=>{if(event.target.id==='search'){ctx.query=event.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(updateResults,140);}if(event.target.hasAttribute('aria-invalid')){event.target.removeAttribute('aria-invalid');const error=document.querySelector(`#error-${event.target.name}`);if(error)error.textContent='';}});
document.addEventListener('submit',event=>{const form=event.target;if(!['filter-form','product-form','delivery-form','payment-form','review-form','contact-form'].includes(form.id))return;event.preventDefault();if(form.id==='filter-form'){clearTimeout(searchTimer);updateResults();}if(form.id==='product-form')productSubmit();if(form.id==='delivery-form'){ctx.checkout.delivery=Object.fromEntries(new FormData(form));const errors=validateDelivery(ctx.checkout.delivery);showErrors(form,errors);if(!Object.keys(errors).length)checkoutStep(1);}if(form.id==='payment-form'){const value=new FormData(form).get('payment');if(!['card-demo','bank-demo'].includes(value))return;ctx.checkout.payment=value;reviewFingerprint=JSON.stringify(cleanCart(ctx.cart,products));checkoutStep(2);}if(form.id==='review-form')completeOrder(form);if(form.id==='contact-form'){const data={...Object.fromEntries(new FormData(form)),consent:form.elements.consent.checked};const errors=validateContact(data);showErrors(form,errors);if(!Object.keys(errors).length){contactDraft={};contactMessage=`Name: ${data.name}\nEmail: ${data.email}\nTopic: ${data.topic}\n\n${data.message}`;document.querySelector('#contact-content').innerHTML=`<div class="contact-success" role="status"><span class="form-success-icon" aria-hidden="true">✓</span><h2>${t(ctx.lang,'送信デモが完了しました','Demo complete.')}</h2><p>${t(ctx.lang,'実際には送信されていません。入力内容は保存されず、画面を閉じると消去されます。','No message has been sent. Your input is not saved and is cleared when the page closes.')}</p><pre class="contact-preview">${e(contactMessage)}</pre><div class="contact-actions"><button class="button" data-action="copy-contact">${t(ctx.lang,'本文をコピー','Copy message')}</button><button class="button button-outline" data-action="reset-contact">${t(ctx.lang,'フォームに戻る','Back to form')}</button></div></div>`;document.querySelector('#contact-content').scrollIntoView({block:'center'});}}});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){const nav=document.querySelector('#mobile-nav');if(nav&&!nav.hidden){nav.hidden=true;document.querySelector('[data-action="menu"]').setAttribute('aria-expanded','false');document.querySelector('[data-action="menu"]').focus();}}});
for(const dialog of [cartDialog,zoomDialog])dialog.addEventListener('click',event=>{if(event.target!==dialog)return;const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();});
window.addEventListener('storage',event=>{if(event.key===KEYS.cart){ctx.cart=cleanCart(readStorage(local,KEYS.cart,[]),products);bagCount();if(cartDialog.open)drawCart();if(['cart','checkout'].includes(ctx.page)){captureDelivery();ctx.checkout.step=0;reviewFingerprint='';renderMain();toast(t(ctx.lang,'別の画面でバッグが更新されました','Your bag was updated in another tab'));}}if(event.key===KEYS.favorites){const list=readStorage(local,KEYS.favorites,[]);ctx.favorites=Array.isArray(list)?list.filter(id=>products.some(p=>p.id===id)):[];if(ctx.page==='store')updateResults();}});
window.addEventListener('popstate',()=>location.reload());
render();
registerStoreTools({getContext:()=>ctx,addToBag:(id,color,size,qty)=>{const p=products.find(p=>p.id===id);const result=addItem(ctx.cart,p,color,size,qty,products);if(!result.ok)throw new Error(result.error);ctx.cart=result.items;persistCart();openCart(true);return {count:totals(ctx.cart,products).count};},removeFromBag:(id,color,size)=>{const key=itemKey(id,color,size);if(!ctx.cart.some(i=>itemKey(i.id,i.color,i.size)===key))throw new Error('Variant is not in the bag.');ctx.cart=ctx.cart.filter(i=>itemKey(i.id,i.color,i.size)!==key);refreshCart();return {count:totals(ctx.cart,products).count};}});
