import { products } from './catalog.mjs';
import { stockFor } from './core.mjs';
export function registerStoreTools(actions) {
 const context=typeof document==='undefined'?undefined:document.modelContext;
 if(!context?.registerTool)return;
 const lifecycle=new AbortController();
 const register=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'aseed_search_products',title:'Find aseed pieces',description:'Read product concepts, prices in JPY, available colours, sizes and demo stock. Does not place orders.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input.query!=='string'||input.query.length>200)throw new Error('Expected a query up to 200 characters.');const q=input.query.toLowerCase();return products.filter(p=>`${p.name} ${p.nameJa} ${p.material.en} ${p.material.ja}`.toLowerCase().includes(q)).map(p=>({id:p.id,name:p.name,priceJPY:p.price,colors:p.colors,sizes:p.sizes,demoStock:p.stock}));}});
 register({name:'aseed_add_to_demo_bag',title:'Add to the demo bag',description:'Stage a product variant in the visible, device-local shopping bag. No real order or payment is created.',inputSchema:{type:'object',properties:{id:{type:'string'},color:{type:'string'},size:{type:'string'},qty:{type:'integer',minimum:1,maximum:9}},required:['id','color','size','qty'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){const p=products.find(p=>p.id===input?.id);if(!p||!p.colors.includes(input.color)||!p.sizes.includes(input.size)||!Number.isInteger(input.qty)||input.qty<1||input.qty>Math.min(9,stockFor(p,input.color,input.size)))throw new Error('Invalid product, variant or quantity.');return actions.addToBag(input.id,input.color,input.size,input.qty);}});
 register({name:'aseed_read_demo_bag',title:'Read the demo bag',description:'Read the current device-local bag. No personal data or real orders are returned.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return {items:actions.getContext().cart.map(i=>({...i}))};}});
 register({name:'aseed_remove_from_demo_bag',title:'Remove from the demo bag',description:'Remove one complete product variant from the visible device-local bag.',inputSchema:{type:'object',properties:{id:{type:'string'},color:{type:'string'},size:{type:'string'}},required:['id','color','size'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input.id!=='string'||typeof input.color!=='string'||typeof input.size!=='string')throw new Error('Expected product id, colour and size.');return actions.removeFromBag(input.id,input.color,input.size);}});
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
